services:
  # Web Service for the Backend
  - type: web
    name: zenith-server
    env: node
    rootDir: Task-1-Zenith/server
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: UI_ROOT_URI
        value: "https://placeholder-for-client-url.com" # We will update this manually later
      - key: SERVER_ROOT_URI
        value: "https://placeholder-for-server-url.com" # We will update this manually later

  # Static Site for the Frontend
  - type: static_site
    name: zenith-client
    rootDir: Task-1-Zenith/client
    buildCommand: "npm run build"
    publishDir: "dist"
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://placeholder-for-server-url.com" # We will update this manually later
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false

